id: I4E71F9E1
ocr_import_info:
  timestamp: '2023-09-23T05:45:46.741894+00:00'
  batch_id: batch-93b6
  ocr_engine: GoogleVisionEngine
  ocr_model_type: builtin/weekly
  ocr_lang_hint: ''
  software_id: ocr-pipelines@v0.1.11
  sponsor: Tenzin Jordhen
  sponsor_consent: true
  op_import_options: {}
  op_import_version: 0.11.7
default_language: bo
source: https://library.bdrc.io
initial_creation_type: ocr
imported: 2023-09-23 06:38:58.259399+00:00
last_modified: 2023-09-23 06:38:58.259405+00:00
source_metadata:
  id: http://purl.bdrc.io/resource/W1NLM3115
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW1NLM3115
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: དབུ་མ་ལ་འཇུག་པའི་ས་བཅད་བསྡུས་དོན་བློ་གསལ་དགའ་སྟོན་སོགས།
  languages:
  - bo
statistics:
  ocr_word_mean_confidence_index: 0.9414347383147965
  ocr_word_median_confidence_index: 0.9963140850000001
bases:
  I1NLM3115_001:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1NLM3115_001
      total_pages: 265
      volume_number: 1
      volume_pages_bdrc_intro: 0
    order: 1
    base_file: I1NLM3115_001.txt
    statistics:
      ocr_word_median_confidence_index: 0.9963140850000001
      ocr_word_mean_confidence_index: 0.9414347383147965
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
